### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by voxpelli** [neostandard/neostandard#10]
10% failed of the top 200 modules using standard `^17.0.0` that was published within the last 550 days. 

Even more fails if `.d.ts` and `.ts` files are parsed and validated as well, which will be the default but is easy to opt out of.

Reasons are as following: 

* [x] - Doesn't support JSX yet - **NEEDS FIX** (#11)
* [x] - Ignore rules don't match the new `@stylistic/` rules - **FIXABLE BY USER**
* [ ] - ESLint no longer recognises eg: `/* eslint-env mocha */` - **FIXABLE BY USER**, although ESLint has made it hard by [removing the `env` options](https://eslint.org/docs/latest/use/configure/migration-guide#eslint-env-configuration-comments) and instead pointing people to use eg: `/* global describe, it -- Globals defined by Mocha */` Doable for Mocha, very verbose for browsers. One alternative is to do: `neostandard({ env: ['mocha'] })`, but that then applies to the entire project. Maybe better solution is needed? (Initial support added in #9)
* [x] - Migrated ignores does not match - **INVESTIGATE?**, this can be fixed by the user, but it may be that something in the migration of them is wrong and can be fixed / improved
* [x] - Runs `standard` with specific files as input rather than using ignores (can't be replicated by other runners) - **FIXABLE BY USER**, they will have to change the command anyhow when they move to `neostandard`
* [x] - `eslint-plugin-promise` rules are not supported yet - **NEEDS FIX** (and needs migration to ESLint 9 / Flat Configs for that plugin, something that I may have to do) (#14)

The 20 out of 200 modules and their reason for failure:

* [bahmutov/simple-bin-help](https://github.com/bahmutov/simple-bin-help) – fails because the `standard` command is fed a list of files to test, rather than using an ignore
* [bcomnes/cpx2](https://github.com/bcomnes/cpx2) – fails because of `/* eslint-env mocha */`
* [bcomnes/npm-run-all2](https://github.com/bcomnes/npm-run-all2) – fails because of `/* eslint-env mocha */`
* [dmonad/lib0](https://github.com/dmonad/lib0) – fails because of `/* eslint-env browser */ `
* [fastify/busboy](https://github.com/fastify/busboy) – fails because the migrated ignore pattern `bench` needs to be `bench/`/ `bench/*` or similar. Also fails because `@stylistic/` rule does not match `/* eslint-disable object-property-newline */ `
* [fastify/deepmerge](https://github.com/fastify/deepmerge) – fails because `@stylistic/` rule does not match `// eslint-disable-line no-mixed-operators`
* [larsgw/sync-fetch](https://github.com/larsgw/sync-fetch) – fails because of `/* eslint-env browser */` and `/* eslint-env mocha */`
* [LinusU/node-application-config-path](https://github.com/LinusU/node-application-config-path) – fails because of `/* eslint-env mocha */`
* [lquixada/cross-fetch](https://github.com/lquixada/cross-fetch) – fails because the migrated `'api.spec.js'` does not match `test/fetch-api/api.spec.js ` + also fails because of missing JSX support
* [mafintosh/streamx](https://github.com/mafintosh/streamx) – fails because `@stylistic/` rule does not match `/* eslint-disable no-multi-spaces */`
* [Maheshkumar-Kakade/otp-generator](https://github.com/Maheshkumar-Kakade/otp-generator) – fails due to `/* eslint-env mocha */ `
* [olahol/react-tagsinput](https://github.com/olahol/react-tagsinput) – fails because the `standard` command is fed a list of files to test, rather than using an ignore + also fails because of missing JSX support
* [rvagg/cborg](https://github.com/rvagg/cborg) – fails because `@stylistic/` rule does not match `// eslint-disable-line operator-linebreak` + fails due to `/* eslint-env mocha */ `
* [svelteness/svelte-jester](https://github.com/svelteness/svelte-jester) – fails because the `standard` command is fed `--env jest` instead of having it defined as `standard.env` in `package.json`, making the migration not pick it up
* [SVG-Edit/svgedit](https://github.com/SVG-Edit/svgedit) – fails because the migrated `'archive/'` ignore doesn't match eg `archive/screencasts/svgopen2010/script.js` + fails because JSX isn't supported yet + fails `eslint-plugin-promise` rules are not supported yet
* [TechTeamer/ocsp](https://github.com/TechTeamer/ocsp) – fails because the `standard` command is fed `--env mocha` instead of having it defined as `standard.env` in `package.json`, making the migration not pick it up
* [testdouble/quibble](https://github.com/testdouble/quibble) – fails because the migrated `['example', 'example-esm']` ignore doesn't match eg `example-esm/test/helper.js` and `example/lib/zoo.js`
* [vimeo/vimeo.js](https://github.com/vimeo/vimeo.js) – fails because of `/* eslint-env mocha */`
* [visionmedia/node-migrate](https://github.com/visionmedia/node-migrate) – fails because of `/* eslint-env mocha */`
* [web3-storage/ipfs-car](https://github.com/web3-storage/ipfs-car) – fails because of `/* eslint-env mocha */`

Extracted failed project from test list using:

```js
[...document.querySelectorAll('.ActionListItem-visual [aria-label="failed: "]')].map(item => item.parentNode.parentNode.parentNode.parentNode.innerText.slice(5))
```

Also added a command to generate and/or migrate standardjs configs:

```sh
neostandard --help
neostandard --semi --migrate > eslint.config.js
```

_Originally posted by @voxpelli in https://github.com/neostandard/neostandard/issues/8#issuecomment-2132190407_

**Comment by voxpelli** [comment]
This might explain the failed `ignore` migrations: https://github.com/typescript-eslint/typescript-eslint/blob/d4504c849eaf309b795c63665cd2cdefa9eeb339/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts#L18-L21

**Comment by voxpelli** [comment]
Ignores are being migrated properly since a while back

**Comment by voxpelli** [comment]
Most compatibility works now, closing and tracking elsewhere
